# Generated by Django 2.1.1 on 2018-09-14 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='in_reply_to_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replied_by', to='Twitter.Tweet'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='in_reply_to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replied_by', to='Twitter.TWUser'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Twitter.TWPlace'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='quoted_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quoted_by', to='Twitter.Tweet'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='retweet_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retweets', to='Twitter.Tweet'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tweets', to='Twitter.TWUser'),
        ),
    ]
