# Generated by Django 2.1.1 on 2018-09-14 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbcomment',
            name='attachment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fbComments', to='Facebook.FBAttachment'),
        ),
        migrations.AlterField(
            model_name='fbcomment',
            name='from_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_comments', to='Facebook.FBProfile'),
        ),
        migrations.AlterField(
            model_name='fbcomment',
            name='parentComment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fbReplies', to='Facebook.FBComment'),
        ),
        migrations.AlterField(
            model_name='fbcomment',
            name='parentPost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fbComments', to='Facebook.FBPost'),
        ),
        migrations.AlterField(
            model_name='fbpage',
            name='featured_video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='featured_on_pages', to='Facebook.FBVideo'),
        ),
        migrations.AlterField(
            model_name='fbpage',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Facebook.FBLocation'),
        ),
        migrations.AlterField(
            model_name='fbpage',
            name='parent_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Facebook.FBPage'),
        ),
        migrations.AlterField(
            model_name='fbpost',
            name='from_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postedStatuses', to='Facebook.FBProfile'),
        ),
        migrations.AlterField(
            model_name='fbpost',
            name='parent_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_posts', to='Facebook.FBPost'),
        ),
        migrations.AlterField(
            model_name='fbreaction',
            name='from_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reacted_to', to='Facebook.FBProfile'),
        ),
        migrations.AlterField(
            model_name='fbreaction',
            name='to_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reactions', to='Facebook.FBComment'),
        ),
        migrations.AlterField(
            model_name='fbreaction',
            name='to_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reactions', to='Facebook.FBPost'),
        ),
    ]
