# Generated by Django 2.1.1 on 2018-10-03 22:29

import SocialNetworkHarvester.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Youtube', '0002_auto_20180914_1818'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Facebook', '0004_auto_20181003_0159'),
        ('Twitter', '0002_auto_20180914_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('created_on', models.DateTimeField(default=SocialNetworkHarvester.models.djangoNow)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collections', to=settings.AUTH_USER_MODEL)),
                ('curators', models.ManyToManyField(related_name='curated_collections', to=settings.AUTH_USER_MODEL)),
                ('facebook_pages', models.ManyToManyField(related_name='collections_included_in', to='Facebook.FBPage')),
                ('followers', models.ManyToManyField(related_name='followed_collections', to=settings.AUTH_USER_MODEL)),
                ('twitter_hashtags', models.ManyToManyField(related_name='collections_included_in', to='Twitter.HashtagHarvester')),
                ('twitter_users', models.ManyToManyField(related_name='collections_included_in', to='Twitter.TWUser')),
                ('youtube_channels', models.ManyToManyField(related_name='collections_included_in', to='Youtube.YTChannel')),
                ('youtube_playlists', models.ManyToManyField(related_name='collections_included_in', to='Youtube.YTPlaylist')),
            ],
        ),
    ]
