# Generated by Django 2.1.1 on 2018-10-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0002_auto_20181003_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
