# Generated by Django 2.1.1 on 2018-10-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0004_auto_20181004_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='facebook_pages',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='twitter_hashtags',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='twitter_users',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='youtube_channels',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='youtube_playlists',
        ),
    ]
