# Generated by Django 2.1.1 on 2018-10-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0006_collectionitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionitem',
            old_name='facebook_pages',
            new_name='facebook_page',
        ),
        migrations.RenameField(
            model_name='collectionitem',
            old_name='twitter_hashtags',
            new_name='twitter_hashtag',
        ),
        migrations.RenameField(
            model_name='collectionitem',
            old_name='twitter_users',
            new_name='twitter_user',
        ),
        migrations.RenameField(
            model_name='collectionitem',
            old_name='youtube_channels',
            new_name='youtube_channel',
        ),
        migrations.RenameField(
            model_name='collectionitem',
            old_name='youtube_playlists',
            new_name='youtube_playlist',
        ),
    ]
