# Generated by Django 2.1.1 on 2018-10-10 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0007_auto_20181005_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_items', to='Collection.Collection'),
        ),
    ]
