# Generated by Django 2.1.1 on 2018-10-23 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0008_auto_20181010_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='twitter_hashtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collections_included_in', to='Twitter.Hashtag'),
        ),
    ]
