# Generated by Django 2.1.1 on 2018-11-07 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0009_auto_20181023_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='Collection.Collection'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='facebook_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections_included_in', to='Facebook.FBPage'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='twitter_hashtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections_included_in', to='Twitter.Hashtag'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='twitter_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections_included_in', to='Twitter.TWUser'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='youtube_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections_included_in', to='Youtube.YTChannel'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='youtube_playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections_included_in', to='Youtube.YTPlaylist'),
        ),
    ]
