# Generated by Django 2.1.1 on 2018-10-12 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0002_auto_20180914_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hashtag',
            options={'verbose_name': 'Hashtag Twitter', 'verbose_name_plural': 'Hashtags Twitter'},
        ),
        migrations.AlterModelOptions(
            name='hashtagharvester',
            options={'verbose_name': 'Hashtag Twitter', 'verbose_name_plural': 'Hashtags Twitter'},
        ),
        migrations.AlterModelOptions(
            name='tweet',
            options={'verbose_name': 'Tweet', 'verbose_name_plural': 'Tweets'},
        ),
        migrations.AlterModelOptions(
            name='twuser',
            options={'verbose_name': 'Utilisateur Twitter', 'verbose_name_plural': 'Utilisateurs Twitter'},
        ),
    ]
