# Generated by Django 2.1.1 on 2018-10-23 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0009_auto_20181023_2239'),
        ('Twitter', '0003_auto_20181012_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtagharvester',
            name='hashtag',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='harvested_by',
        ),
        migrations.DeleteModel(
            name='HashtagHarvester',
        ),
    ]
