# Generated by Django 2.1.1 on 2018-10-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0004_auto_20181023_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='_update_frequency',
            field=models.IntegerField(default=5),
        ),
    ]
