# Generated by Django 2.1.1 on 2018-11-03 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0006_hashtagharvester'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtagharvester',
            name='hashtag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Twitter.Hashtag'),
        ),
    ]
