# Generated by Django 2.1.1 on 2018-10-23 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AspiraUser', '0002_auto_20180712_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='twitterUsersToHarvest',
        ),
    ]
