# Generated by Django 2.1.1 on 2018-10-23 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AspiraUser', '0003_auto_20181023_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='facebookPagesToHarvest',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ytChannelsToHarvest',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ytPlaylistsToHarvest',
        ),
    ]
