# Generated by Django 2.1.1 on 2018-10-23 18:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0003_auto_20181012_0029'),
        ('Facebook', '0005_auto_20181012_0029'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Youtube', '0004_auto_20181019_2151'),
        ('AspiraUser', '0004_auto_20181023_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemHarvester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_from', models.DateTimeField(default=datetime.datetime(2018, 9, 23, 0, 0, tzinfo=utc))),
                ('harvest_until', models.DateTimeField(default=datetime.datetime(2018, 10, 23, 0, 0, tzinfo=utc))),
                ('facebook_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='harvested_by', to='Facebook.FBPage')),
                ('twitter_hashtag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='harvested_by', to='Twitter.HashtagHarvester')),
                ('twitter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='harvested_by', to='Twitter.TWUser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvested_items', to=settings.AUTH_USER_MODEL)),
                ('youtube_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='harvested_by', to='Youtube.YTChannel')),
                ('youtube_playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='harvested_by', to='Youtube.YTPlaylist')),
            ],
        ),
    ]
