# Generated by Django 2.1.1 on 2018-10-23 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AspiraUser', '0006_auto_20181023_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemharvester',
            name='twitter_hashtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='harvested_by', to='Twitter.Hashtag'),
        ),
    ]
