# Generated by Django 2.1.1 on 2018-10-27 20:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AspiraUser', '0007_auto_20181023_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemharvester',
            name='harvest_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemharvester',
            name='harvest_since',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itemharvester',
            name='harvest_until',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 27, 0, 0, tzinfo=utc)),
        ),
    ]
