# Generated by Django 2.1.1 on 2018-10-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AspiraUser', '0008_auto_20181027_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemharvester',
            name='harvest_since',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='itemharvester',
            name='harvest_until',
            field=models.DateTimeField(),
        ),
    ]
