# Generated by Django 2.1.1 on 2018-10-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook', '0003_auto_20181002_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbattachment',
            name='type',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
