# Generated by Django 2.1.1 on 2018-10-12 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook', '0004_auto_20181003_0159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fbpage',
            options={'verbose_name': 'Page Facebook', 'verbose_name_plural': 'Pages Facebook'},
        ),
    ]
