# Generated by Django 2.1.1 on 2018-10-12 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0002_auto_20180914_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ytchannel',
            options={'verbose_name': 'Chaîne Youtube', 'verbose_name_plural': 'Chaînes Youtube'},
        ),
        migrations.AlterModelOptions(
            name='ytcomment',
            options={'verbose_name': 'Commentaire Youtube', 'verbose_name_plural': 'Commentaires Youtube'},
        ),
        migrations.AlterModelOptions(
            name='ytplaylist',
            options={'verbose_name': 'Playlist Youtube', 'verbose_name_plural': 'Playlists Youtube'},
        ),
        migrations.AlterModelOptions(
            name='ytplaylistitem',
            options={'verbose_name': 'Élément de playlis Youtube', 'verbose_name_plural': 'Éléments de playlist Youtube'},
        ),
        migrations.AlterModelOptions(
            name='ytvideo',
            options={'verbose_name': 'Video Youtube', 'verbose_name_plural': 'Videos Youtube'},
        ),
    ]
