# Generated by Django 2.1.1 on 2018-10-19 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0003_auto_20181012_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ytplaylistitem',
            options={'verbose_name': 'Élément de playlist Youtube', 'verbose_name_plural': 'Éléments de playlist Youtube'},
        ),
    ]
